export const fonts = {
    SFPRODISPLAYBLACKITALIC: require('./SFPRODISPLAYBLACKITALIC.ttf'),
    SFPRODISPLAYBOLD: require('./SFPRODISPLAYBOLD.ttf'),
    SFPRODISPLAYHEAVYITALIC: require('./SFPRODISPLAYHEAVYITALIC.ttf'),
    SFPRODISPLAYMEDIUM: require('./SFPRODISPLAYMEDIUM.ttf'),
    SFPRODISPLAYREGULAR: require('./SFPRODISPLAYREGULAR.ttf'),

}