import { Background } from "@react-navigation/elements";
import { Share } from "react-native";

export const assets = {
  about: require("./About.png"),
  arrowWhite:require("./arrowWhite.png"),
  ArrowLeft: require("./ArrowLeft.png"),
  arrowBlack:require("./arrowBlack.png"),
  blackBg:require("./black.jpeg"),
  bannerLight:require("./bannerLight.png"),
  bannerDark:require("./bannerDark.png"),
  blackplus:require("./blackPlus.png"),
  BagBlue: require("./BagBlue.png"),
  BagBlack:require("./BagBlack.png"),
  Bag: require("./Bag.png"),
  BackgroundCollection1: require("./BackgroundCollection1.png"),
  BannerCarousel: require("./Banner.png"),
  bigSale:require("./bigSale.png"),
  bigSale1:require("./bigSale1.png"),
  Background:require("./Background.jpeg"),
  BackgroundDark:require("./DarkBackground.png"),
  blackOutlineHeart:require("./blackoutlineHeart.png"),
  backArrow:require("./backicon.png"),
  Collection1: require("./Collection1.png"),
  category: require("./Categories.png"),
  Clock: require("./clock.png"),
  Demo: require("./demo.png"),
  Deal1: require("./Deal1.png"),
  Deal2: require("./Deal2.png"),
  Deal3: require("./Deal3.png"),
  Deal4: require("./Deal4.png"),
  DownArray: require("./DownArray.png"),
  Down: require("./down.png"),
  exchange:require("./exchange.png"),
  exchangeWhite:require("./exchangewhite.png"),
  facebooklogo: require("./Facebook.png"),
  Filter: require("./filter.png"),
  googlelogo: require("./Google.png"),
  Home: require("./Home.png"),
  HomeBlue: require("./HomeBlue.png"),
  Heart: require("./Heart.png"),
  HeartBlue: require("./HeartBlue.png"),
  HeartBlack: require("./HeartBlack.png"),
  help: require("./Help.png"),
  homeIcon:require("./homeIcon.png"),
  kids: require("./kids.png"),
  heart: require("./smallheart.png"),
  LogoFor21: require("./LogoFor21.png"),
  LogoZara: require("./LogoZara.png"),
  LogoMango: require("./LogoMango.jpg"),
  LogoPuma: require("./LogoPuma.jpg"),
  LogoHM: require("./LogoHM.png"),
  logofirst: require("./firstlogo.png"),
  Location: require("./location.png"),
  Logout: require("./logout.png"),
  left: require("./Left.png"),
  men: require("./men.png"),
  message: require("./Message.png"),
  MainSearch: require("./MainSearch.png"),
  Notification:require("./Bell_pin.png"),
  NotificationLight:require("./Bell_pin black.png"),
  name: require("./Name.png"),
  OfferBackground:require("./Voucher.png"),
  offerGif:require("./offer.gif"),
  offerWhite:require("./offerWhite.gif"),
  Offers: require("./offers.png"),
  officeIcon:require("./officeIcon.png"),
  OrderImage:require("./Order.png"),
  OrderBlack:require("./orderBlack.png"),
  password: require("./Password.png"),
  Payment: require("./payment.png"),
  plus:require("./plus.png"),
  Razorpay: require("./Razorpay.png"),
  rightarrow: require("./Vector.png"),
  redHeart:require("./redHeart.png"),
  Search: require("./Search.png"),
  SearchBlue: require("./SearchBlue.png"),
  SmallCollection1: require("./SmallCollection1.png"),
  Share: require("./Share.png"),
  TrendCard: require("./TrendCard.png"),
  tote: require("./tote.png"),
  women: require("./women.png"),
  Western: require("./WesternWear.png"),
  WhiteBag: require("./WhiteBag.png"),
  User: require("./User.png"),
  UserBlue: require("./UserBlue.png"),
  UserImage: require("./UserImage.png"),
  Up: require("./Up.png"),
};
