
export const assets = {
    category: require('./Categories.png'),
    men:require('./men.png'),
    women:require('./women.png'),
    kids:require('./kids.png'),
    Western:require('./WesternWear.png'),
    Home:require('./Home.png'),
    HomeBlue:require('./HomeBlue.png'),
    Search:require('./Search.png'),
    SearchBlue:require('./SearchBlue.png'),
    Heart:require('./Heart.png'),
    HeartBlue:require('./HeartBlue.png'),
    Bag:require('./Bag.png'),
    BagBlue:require('./BagBlue.png'),
    User:require('./User.png'),
    UserBlue:require('./UserBlue.png'),
    Collection1:require('./Collection1.png'),
    SmallCollection1:require('./SmallCollection1.png'),
    BackgroundCollection1:require('./BackgroundCollection1.png'),
    BannerCarousel:require('./Banner.png'),
    TrendCard:require('./TrendCard.png'),
    LogoFor21:require('./LogoFor21.png'),
    LogoZara: require('./LogoZara.png'),
    LogoMango: require('./LogoMango.jpg'),
    LogoPuma: require('./LogoPuma.jpg'),
    LogoHM: require('./LogoHM.png'),
    UserImage:require('./UserImage.png'),
    MainSearch: require('./MainSearch.png')
}  