const ENDPOINTS = {
  USERS: "/user",
  LOGIN: "/user/login",
  GOOGLELOGIN: "/user/login-with-google",
  FORGET_PASSWORD: "/user/forget-password",
  VERIFY_OTP: "/user/verify-otp",
  UPDATE_PASSWORD: "/user/update-password",
  CHANGE_PASSWORD: "/user/change-password",
  UPDATE: (id: string) => `/user/${id}`,
  DELETE: "/user/",
  CATEGORY: "/categories/all-categories",
  SUBCATEGORY: "/categories/",
  PRODUCTS: "/categories/",
  CAROUSAL: "/product/get-carousel",
  WISHLIST: "/wishlist",
  WISHLISTGET: "/wishlist/get-wishlist",
  WISHLISTPOST: "/wishlist/create",
  WISHLISTDELETE: "/wishlist/wishlist-delete",
  COLLECTION: "/product/get-products",
  FILTERS: "/product/filter",
  CART: "/cart",
  CARTDELETE: "cart/remove",
  QUANTITYDELETE: "cart/quantity",
  PROMOCODE: "/promocode",
  PROMOCODEPOST: "/promocode/apply",
  SEARCHALL: "/product/search",
  PAYMENT: "/order/razorpay",
  UPLOADS: "/user/upload",
  ALLORDERS: "/order",
  COLOR: "/color",
  BRAND:"/brand"
};

export default ENDPOINTS;
