import { assets } from "../assets/images";

// export const HeaderData =
// {
//     userName: 'Anna Doe ',
//     // userImage: assets.UserImage,
//     icon: assets.MainSearch,
// }

export const BannerData = [
  {
    id: "1",
    image: assets.BannerCarousel,
    logoImage: assets.LogoFor21,
    brand: "Shirts",
    event: "Big Fashion Festival",
    discount: "70%-80% off",
  },
  {
    id: "2",
    image: assets.BannerCarousel,
    logoImage: assets.LogoHM,
    brand: "T-Shirts",
    event: "Summer Fashion Sale",
    discount: "60%-70% off",
  },
  {
    id: "3",
    image: assets.BannerCarousel,
    logoImage: assets.LogoZara,
    brand: "Jackets",
    event: "Winter Fashion Sale",
    discount: "70% - 80% off",
  },
  {
    id: "4",
    image: assets.BannerCarousel,
    logoImage: assets.LogoMango,
    brand: "Shoes",
    event: "Spring Fashion Sale",
    discount: "60% - 70% off",
  },
  {
    id: "5",
    image: assets.BannerCarousel,
    logoImage: assets.LogoPuma,
    brand: "Jeans",
    event: "Sports Fashion Sale",
    discount: "70% - 80% off",
  },
  {
    id: "6",
    image: assets.BannerCarousel,
    logoImage: assets.LogoFor21,
    brand: "Trousers",
    event: "Big Fashion Festival",
    discount: "70%-80% off",
  },
  {
    id: "7",
    image: assets.BannerCarousel,
    logoImage: assets.LogoFor21,
    brand: "Watches",
    event: "Big Fashion Festival",
    discount: "70%-80% off",
  },
];

export const BannerData1 = [
  {
    id: "1",
    image: assets.BannerCarousel,
    logoImage: assets.LogoFor21,
    brand: "T-Shirts",
    event: "Big Fashion Festival",
    discount: "70%-80% off",
  },
  {
    id: "2",
    image: assets.BannerCarousel,
    logoImage: assets.LogoZara,
    brand: "Jackets",
    event: "Winter Fashion Sale",
    discount: "70% - 80% off",
  },
  {
    id: "3",
    image: assets.BannerCarousel,
    logoImage: assets.LogoMango,
    brand: "Shoes",
    event: "Spring Fashion Sale",
    discount: "60% - 70% off",
  },
  {
    id: "4",
    image: assets.BannerCarousel,
    logoImage: assets.LogoPuma,
    brand: "Jeans",
    event: "Sports Fashion Sale",
    discount: "70% - 80% off",
  },
  {
    id: "5",
    image: assets.BannerCarousel,
    logoImage: assets.LogoFor21,
    brand: "Trousers",
    event: "Big Fashion Festival",
    discount: "70%-80% off",
  },
  {
    id: "6",
    image: assets.BannerCarousel,
    logoImage: assets.LogoFor21,
    brand: "Watches",
    event: "Big Fashion Festival",
    discount: "70%-80% off",
  },
  {
    id: "7",
    image: assets.BannerCarousel,
    logoImage: assets.LogoHM,
    brand: "Shirts",
    event: "Summer Fashion Sale",
    discount: "60%-70% off",
  },
  {
    id: "8",
    image: assets.BannerCarousel,
    logoImage: assets.LogoHM,
    brand: "Suits",
    event: "Summer Fashion Sale",
    discount: "60%-70% off",
  },
  {
    id: "9",
    image: assets.BannerCarousel,
    logoImage: assets.LogoHM,
    brand: "kurtis",
    event: "Summer Fashion Sale",
    discount: "60%-70% off",
  },
  {
    id: "10",
    image: assets.BannerCarousel,
    logoImage: assets.LogoHM,
    brand: "Sarees",
    event: "Summer Fashion Sale",
    discount: "60%-70% off",
  },
];

export const BannerData2 = [
  {
    id: "1",
    image: assets.BannerCarousel,
    logoImage: assets.LogoFor21,
    brand: "T-Shirts",
    event: "Big Fashion Festival",
    discount: "70%-80% off",
  },
  {
    id: "2",
    image: assets.BannerCarousel,
    logoImage: assets.LogoZara,
    brand: "Jackets",
    event: "Winter Fashion Sale",
    discount: "70% - 80% off",
  },
  {
    id: "3",
    image: assets.BannerCarousel,
    logoImage: assets.LogoMango,
    brand: "Shoes",
    event: "Spring Fashion Sale",
    discount: "60% - 70% off",
  },
  {
    id: "4",
    image: assets.BannerCarousel,
    logoImage: assets.LogoPuma,
    brand: "Jeans",
    event: "Sports Fashion Sale",
    discount: "70% - 80% off",
  },
  {
    id: "5",
    image: assets.BannerCarousel,
    logoImage: assets.LogoFor21,
    brand: "Watches",
    event: "Big Fashion Festival",
    discount: "70%-80% off",
  },
  {
    id: "6",
    image: assets.BannerCarousel,
    logoImage: assets.LogoHM,
    brand: "Shirts",
    event: "Summer Fashion Sale",
    discount: "60%-70% off",
  },
  {
    id: "7",
    image: assets.BannerCarousel,
    logoImage: assets.LogoHM,
    brand: "Suits",
    event: "Summer Fashion Sale",
    discount: "60%-70% off",
  },
  {
    id: "8",
    image: assets.BannerCarousel,
    logoImage: assets.LogoHM,
    brand: "kurtis",
    event: "Summer Fashion Sale",
    discount: "60%-70% off",
  },
];

export const BannerData3 = [
  {
    id: "1",
    image: assets.BannerCarousel,
    logoImage: assets.LogoFor21,
    brand: "Hats",
    event: "Big Fashion Festival",
    discount: "70%-80% off",
  },
  {
    id: "2",
    image: assets.BannerCarousel,
    logoImage: assets.LogoZara,
    brand: "Gowns",
    event: "Winter Fashion Sale",
    discount: "70% - 80% off",
  },
  {
    id: "3",
    image: assets.BannerCarousel,
    logoImage: assets.LogoMango,
    brand: "Coats",
    event: "Spring Fashion Sale",
    discount: "60% - 70% off",
  },
  {
    id: "4",
    image: assets.BannerCarousel,
    logoImage: assets.LogoPuma,
    brand: "Trousers",
    event: "Sports Fashion Sale",
    discount: "70% - 80% off",
  },
  {
    id: "5",
    image: assets.BannerCarousel,
    logoImage: assets.LogoFor21,
    brand: "Footwear",
    event: "Big Fashion Festival",
    discount: "70%-80% off",
  },
];

export const BannerData4 = [
  {
    id: "1",
    image: assets.BannerCarousel,
    logoImage: assets.LogoFor21,
    brand: "Kurtis",
    event: "Big Fashion Festival",
    discount: "70%-80% off",
  },
  {
    id: "2",
    image: assets.BannerCarousel,
    logoImage: assets.LogoZara,
    brand: "Sarees",
    event: "Winter Fashion Sale",
    discount: "70% - 80% off",
  },
  {
    id: "3",
    image: assets.BannerCarousel,
    logoImage: assets.LogoMango,
    brand: "Salwar Kameez",
    event: "Spring Fashion Sale",
    discount: "60% - 70% off",
  },
  {
    id: "4",
    image: assets.BannerCarousel,
    logoImage: assets.LogoPuma,
    brand: "Sherwani",
    event: "Sports Fashion Sale",
    discount: "70% - 80% off",
  },
  {
    id: "5",
    image: assets.BannerCarousel,
    logoImage: assets.LogoFor21,
    brand: "Dhoti kurta",
    event: "Big Fashion Festival",
    discount: "70%-80% off",
  },
  {
    id: "6",
    image: assets.BannerCarousel,
    logoImage: assets.LogoFor21,
    brand: "Anarkali Suits",
    event: "Big Fashion Festival",
    discount: "70%-80% off",
  },
];

export const CardData = [
  {
    id: "1",
    img: assets.TrendCard,
    logo: assets.LogoHM,
    offer: 30,
  },
  {
    id: "2",
    img: assets.TrendCard,
    logo: assets.LogoZara,
    offer: 40,
  },
  {
    id: "3",
    img: assets.TrendCard,
    logo: assets.LogoMango,
    offer: 50,
  },
  {
    id: "4",
    img: assets.TrendCard,
    logo: assets.LogoHM,
    offer: 50,
  },
  {
    id: "5",
    img: assets.TrendCard,
    logo: assets.LogoPuma,
    offer: 30,
  },
  {
    id: "6",
    img: assets.TrendCard,
    logo: assets.LogoZara,
    offer: 70,
  },
  {
    id: "7",
    img: assets.TrendCard,
    logo: assets.LogoMango,
    offer: 20,
  },
  {
    id: "8",
    img: assets.TrendCard,
    logo: assets.LogoHM,
    offer: 30,
  },
];
export const DealData = [
  {
    id: "1",
    img: assets.Deal1,
    productType: "Tops",
    amount: 3000,
  },
  {
    id: "2",
    img: assets.Deal2,
    productType: "Tshirt",
    amount: 300,
  },
  {
    id: "3",
    img: assets.Deal3,
    productType: "Shirt",
    amount: 5000,
  },
  {
    id: "4",
    img: assets.Deal4,
    productType: "Tops",
    amount: 1000,
  },
  {
    id: "5",
    img: assets.Deal4,
    productType: "Skirt",
    amount: 300,
  },
  {
    id: "6",
    img: assets.Deal3,
    productType: "Bags",
    amount: 3000,
  },
  {
    id: "7",
    img: assets.Deal2,
    productType: "Accessories",
    amount: 30000,
  },
  {
    id: "8",
    img: assets.Deal1,
    productType: "Tops",
    amount: 1500,
  },
];

export const ProductData = [
  {
    id: "2",
    images: [
      assets.Collection1,
      assets.SmallCollection1,
      assets.BackgroundCollection1,
    ],
    productName: "Womens White Shirt ",
    brandName: "Brand Name",
    initialRate: 999127,
    rate: 799,
    discount: "20",
  },
  {
    id: "3",
    images: [
      assets.Collection1,
      assets.SmallCollection1,
      assets.Collection1,
      assets.SmallCollection1,
      assets.BackgroundCollection1,
    ],
    productName: "Womens White Shirt",
    brandName: "Brand Name",
    initialRate: 999,
    rate: 799,
    discount: "20",
  },
  {
    id: "4",
    images: [
      assets.Collection1,
      assets.SmallCollection1,
      assets.BackgroundCollection1,
      assets.Collection1,
      assets.SmallCollection1,
      assets.BackgroundCollection1,
    ],
    productName: "Womens White Shirt",
    brandName: "Brand Name",
    initialRate: 999,
    rate: 799,
    discount: "20",
  },
  {
    id: "5",
    images: [
      assets.Collection1,
      assets.SmallCollection1,
      assets.BackgroundCollection1,
    ],
    productName: "Womens White Shirt",
    brandName: "Brand Name",
    initialRate: 999,
    rate: 799,
    discount: "20",
  },
  {
    id: "6",
    images: [
      assets.Collection1,
      assets.SmallCollection1,
      assets.BackgroundCollection1,
    ],
    productName: "Womens White Shirt",
    brandName: "Brand Name",
    initialRate: 999,
    rate: 799,
    discount: "20",
  },
];
